### PR TITLE
Add Hebrew Language in Installation Options

### PR DESCRIPTION
**Pull request by elishl**

### CODE REVIEW

**Comment by oberon2007** [comment]
Since all other languages are using their native name, the title should acutlly be in Hebrew I'd say. :)

**Comment by elishl** [comment]
Bernhard, you're absolutely right.
I've edited the PR.

Thanks.

**Comment by oberon2007** [comment]
Thanks :)

**Comment by elishl** [comment]
Thank you.
If possible, please add the changes for the next installment of Manjaro (17.0.3).
Thanks again.

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-extra/commit/2b5d82a64fe92507263cb763069db7bf24e110bd

**Comment by elishl** [comment]
Thanks for your time.
Appreciate it...:-)

**Pull request merged**
